pipeline:
  name: git-harness-ci-uk
  identifier: githarnessciuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githarnessuk
        build: <+input>
  stages:
    - stage:
        name: first_build
        identifier: first_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Git-Checkout
                  identifier: GitCheckout
                  spec:
                    connectorRef: githarnessuk
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Install_Dependencies
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Installiing dependencies"
                      sudo apt update -y
                      sudo apt install -y nodejs npm
                      npm install
              - step:
                  type: Run
                  name: Run_Script
                  identifier: Run_Script
                  spec:
                    shell: Sh
                    command: |-
                      echo "Running script"
                      node src/index.js
              - step:
                  type: Run
                  name: Run_Test
                  identifier: Run_Test
                  spec:
                    shell: Sh
                    command: |-
                      echo "Running Tests"
                      npm test
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
        delegateSelectors:
          - docker-delegate
