pipeline:
  name: git-harness-ci-uk
  identifier: githarnessciuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githarnessuk
        build: <+input>
  stages:
    - stage:
        name: first_build
        identifier: first_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_Packer
                  identifier: Run_Packer
                  spec:
                    shell: Sh
                    command: |-
                      echo "Executing packer"
                      sudo packer init gcp-image.pkr.hcl
                      sudo packer build gcp-image.pkr.hcl
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
        delegateSelectors:
          - docker-delegate
