pipeline:
  name: git-harness-ci-uk
  identifier: githarnessciuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githarnessuk
        build: <+input>
  stages:
    - stage:
        name: first_build
        identifier: first_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "HEllo world"
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        delegateSelectors:
          - docker-delegate
