pipeline:
  name: git-harness-ci-uk
  identifier: githarnessciuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githarnessuk
        build: <+input>
  stages:
    - stage:
        name: first_build
        identifier: first_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_Packer
                  identifier: Run_Packer
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update -y
                      echo "instlliing unzip"
                      sudo apt install unzip -y
                      echo "downloding packer"
                      sudo curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
                      echo "testing 1"
                      unzip -o packer.zip
                      sudo mv packer /usr/local/bin/
                      sudo chmod +x /usr/local/bin/packer

                      packer --version
                      echo "Executing packer"
                      touch packer_dir/main.pkr.hcl
                      cat packer_dir/variables.pkr.hcl packer_dir/source.pkr.hcl packer_dir/provisioners.pkr.hcl > packer_dir/main.pkr.hcl

                      packer init packer_dir/main.pkr.hcl
                      packer validate -var-file=packer_dir/dev.pkvars.hcl packer_dir/main.pkr.hcl
                      packer build -var-file=packer_dir/dev.pkvars.hcl packer_dir/main.pkr.hcl
                      rm -rf packer_dir/main.pkr.hcl
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
        delegateSelectors:
          - docker-delegate
